env:
  global:
    secure: AT5Gn0HXXg/y3hO0KFR7Y91JG4Z9Shz5MJB9DrMHywelroWn3b4lWu4RVGZAkvCFa5QyfxFcseCwsv8k1kUVx1Bi0Lmsa4VviJuvEsuY5cjyoM15B/d5Qdx3Cwy3VoNdYXGYNdI+q6rcMkB86bTwnAtmZKLj6P3RWAZ7BLuGc1IzZW/j3YTpN4ks+Gir9TMzcFV9xwfYmG2xcASzUM2gMMWTGFp2IezGUQRXGgz0hRjbvvkQ9Oh5VqoUgE3HkOrSMVeBulv8zoCJg4/xbYg26v3CbFSLvgEEpj/7wAKvynGa8YEl50brTrvZjJHAqGe3K0g4W9B9vF1ScbnjABirlu+cii2O90If/KyzBzZoXyxCwuBiEXtGEFpsstwe+0J4jNVPJGKhDsVYSGF5mEO6RvSyz4r23g74NSX52+Jj4emD7WG1e6ZKUiiYCauvvin11LTca294Dv71TVQQjxxvOvtA049YYR/ixzU7Jzjinrb3R+9t+AYdAO0b4IIL5aE58ZL0TKS2VOCNxeVTDMxYa/wks1t+o5EVAy2pZvIPhGP+2IuJUahpmkox90LsATWATBfdMlNoS2wyDXNI6kNRzJEVW9w7DXjBvG0tkoQo4AyKYdjv/ee3QGmbj0iZZHzb1L4g5F2DvnqnX0faKm4QvtaYJpsV0CqPExCMhdopf7I=
git:
  depth: 1
language: node_js
node_js: node
cache:
  directories:
  - node_modules
before_script:
- npm install esprima
script:
- node "./Continuous Integration/1-pretest.node.js"
- node "./Continuous Integration/2-test-1-syntax.node.js"
- node "./Continuous Integration/2-test-2-content-core.node.js"
- node "./Continuous Integration/3-build.node.js"
