env:
  global:
  - secure: TTdJr43pTt/pJT25mQBjTtiCRTuYkTC+Jg6qkkjKJh66UQtWdMusvXPcM/o33ylxxYnpOCUhnQzFXEAu+bBok8zLx/jsuLYrFIfoAWV0j9N5jCOiS6rmdobdErnFuG4tf2gWnr6IRMXkxAzZCXqJOBnafMyWo3xip8R1ZxICB2z4He6j47+Qa1Pb+epR4sowuhIqsrv4msG/7qYsON5Wbyg8dQoabazh96Ww94NPVATdxSB6DRPcuznaYgUDJOlXPBXmE0x8tG9WluiFHEmf+KkuKPvigFhy4SZr/s0dWhaczpMrkiyVwqKF3VXS+YY9wtpcB4gUI7SlTiWLJ5YiVOAvpIsAkzqnkREHjn8lnLsUk0C8+tyi4fxBtAMf52mfOGrqkhyrKzI3di6YF55vwkhc+lmjF2T8csuPYVw67LSTnfYbrj/Sxqx7u69SDhf9IuD4ofWCkb5SPKRUl4wVTnVAYJ793b+zkQfc5S3HMRHzkWSDk2qTpCCRaG64mLvwXg0JjnE5vdR8ZKHYZtaBP1rn6iJ2Y28cpkVOKTIoSaBNmSxwgUiYh6M7iqfdh5GCkacIkejnUQkuK7wFli2Sk/NGdWZs+drlWOY5ZXpu1o5M5XbhSBBVJ/tEuxAQmiSTuTCE7u5aPG5HUYBQlIDLeTb9ngBba1KUF66AaRQRfvw=
  - secure: RgImx9hYFJnECKnZbKAqNWnPLkJwRjYtujlBrFSuJ/ebn27snlfABYTuaUWYI5TMftxV8jp+UaA+Usi7/TOeHiCmHVBCC9FHOgp0kU+BMuWhhHd+G27jDGaAjPZVs05JoDGOXmb8JCLya4qgVlJxTDOO8mBwnGxH4RR6J9HDmO/WzvtOyIC8E9Ek7ozS+4t2EmR1QG7ZNg06e97FVGzp0P9qX+j8HFzGOnXGC4O7A5q1NAM/kiqJc63VSZzT8gUI+cAC4/l2CXMteAzaLV+iodVYXV7kCyvPJYQlFcGLG4cpFvNNXbRKQcL7sazZt9HHa2yC/dt5hEAqLIdkZOwH3/MnoeamedT4jj9sEwI1q7mWFRTd3ayOKbhrCb9DG50/+6khaBFQioxR2KoPoOMRPzm80YNCfRMvyASLljhVc+bCUFrEFOjMZg1k/ruTgR8Q2+xGNeRaL088/F0Ebx1jY4E21jHczC9jdYH6JQVGgn+q/YfLYhusEuBufUJyevp7h0fJv98IjFL/c8KczwOXPqz/5EmzEMP3p9s8FksGzAOYDESi5WqRvZmZ4HY+LEJh2Lrc4TlE1Pv8frhii6A/gmXnjuyiLDJUO+UrrrpO7xOx8yTIPRHRXZZFyblQXdvhRGUfXzYQWEOTkPEgv983CtKqVls0NAENxoTlGfiG2DA=
git:
  depth: 1
language: node_js
node_js: node
cache:
  directories:
  - node_modules
before_script:
- npm install esprima
script:
- node "./Continuous Integration/1-pretest.node.js"
- node "./Continuous Integration/2-test-1-syntax.node.js"
- node "./Continuous Integration/2-test-2-content-core.node.js"
- node "./Continuous Integration/3-build.node.js"
