git:
  depth: 1
language: node_js
node_js: node
cache:
  directories:
    - "node_modules"
before_script:
  - npm install esprima
script:
  - node "./Continuous Integration/1-pretest.node.js"
  - node "./Continuous Integration/2-test-1-syntax.node.js"
  - node "./Continuous Integration/2-test-2-content-core.node.js"
  - node "./Continuous Integration/3-build.node.js"
