git:
  depth: 1
language: node_js
node_js: node
cache:
  directories:
    - "node_modules"
before_script:
  - npm install esprima
script:
  - node ./Tests/1-pretest.node.js
  - node ./Tests/2-syntax.node.js
  - node ./Tests/3-content-core.node.js
